<a href="https://colab.research.google.com/github/LucasCabra7/precos-combustiveis-brasil-2015-2025/blob/main/Grupo_4_An%C3%A1lise_Explorat%C3%B3ria_e_Modelagem_Preditiva_dos_Pre%C3%A7os_de_Combust%C3%ADveis_no_Brasil_(2015%E2%80%932025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise Exploratória e Modelagem Preditiva dos Preços de Combustíveis no Brasil (2015–2025)

## 1. Descrição do Dataset

O presente projeto tem como objetivo analisar e compreender o comportamento dos preços de combustíveis no Brasil ao longo do tempo, utilizando dados públicos disponibilizados pela Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP).

[O conjunto de dados utilizado](https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/serie-historica-de-precos-de-combustiveis) consiste na série histórica de preços de combustíveis, contendo informações coletadas semanalmente em diversos postos distribuídos por estados e municípios brasileiros.

A base de dados inclui variáveis relevantes como localização geográfica (estado e município), tipo de combustível (gasolina, etanol, diesel, entre outros), datas de coleta e valores de compra e venda.

Para este estudo, foi selecionado o período de [**2015 a 2025** para o Dataset de estudo](https://drive.google.com/file/d/1HSjbMjqx4OD4beNF-mkqOMiha7mFKUl6/view?usp=sharing), por apresentar maior consistência nos dados e englobar eventos econômicos significativos que impactaram diretamente os preços dos combustíveis, como a crise econômica brasileira, a greve dos caminhoneiros em 2018 e a pandemia de COVID-19 em 2020.


* 2016 - Crise econômica do Brasil
* 2018 - Greve dos Caminhoneiros (impacto direto no combustível)
* 2020 - Pandemia (Covid-19)
* 2022 - Alta global do combustível

---


O conjunto de dados consolidado possui **9889848** instâncias (linhas) e **17** atributos (colunas). As variáveis estão divididas em tipos distintos: categóricas (como estado, município, produto e bandeira), numéricas contínuas (como valor de compra e valor de venda) e temporais (data da coleta).

Do ponto de vista prático, a compreensão desses dados permite aplicações como a previsão de custos operacionais para o setor de transporte e o monitoramento de anomalias mercadológicas.

Com base nesse contexto, o estudo configura-se como um problema de Regressão / Classificação, visto que o objetivo futuro da modelagem será prever o valor contínuo do combustível nas bombas / categorizar a tendência do mercado como alta, baixa ou estável.

## 2. Estruturação do Projeto

#### 2.1. Importações

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import drive

#### 2.2. Caminho para o Dataset e correções

In [ ]:
drive.mount('/content/drive')

# Caminho para o Google Drive - Dataset
caminho_dataset = '/content/drive/MyDrive/Projeto - Ciências de Dados (Grupo 4)/Dataset 2015 - 2025 (Separados)/Dataset_Completo_2015_2025.csv'

print("Carregando o dataset completo.... Aguarde!")
data_Frame = pd.read_csv(caminho_dataset, sep=';', low_memory=False)

# Correção de ',' para '.' no Valor de Venda
data_Frame['Valor de Venda'] = data_Frame['Valor de Venda'].str.replace(',', '.').astype(float)

print(f"Dataset carregado com sucesso! Total de linhas: {len(data_Frame)}")

Mounted at /content/drive
Carregando o dataset completo.... Aguarde!
Dataset carregado com sucesso! Total de linhas: 9889848

## 3. Análises Estatísticas Descritivas

### 3.1.0 Análise Exploratória Inicial do Dataset

Análise exploratória Inicial com o objetivo de compreender a estrutura e os principais elementos da base de dados utilizada.

O dataset apresenta informações relacionadas à comercialização de combustíveis no Brasil no período de 2015 a 2025.

Entre as variáveis analisadas, destacam-se:

* Produto: identifica o tipo de combustível comercializado, sendo os principais gasolina, etanol, diesel e GNV;
* Município e Região: permitem a análise geográfica dos dados, evidenciando a distribuição espacial das observações;
* Unidade de Medida: associada ao tipo de combustível, indicando a forma de comercialização (por exemplo, litros ou metros cúbicos);
* Bandeira: representa a marca ou distribuidora associada ao posto de combustíveis.

A análise das frequências dos produtos revelou quais combustíveis possuem maior representatividade na base. Além disso, a distribuição dos municípios por região permitiu identificar a cobertura geográfica da pesquisa.

In [ ]:
print("\n ---- VISÃO GERAL DO DATASET ----\n")

print("Dimensões do dataset:")
print(f"Linhas: {data_Frame.shape[0]}")
print(f"Colunas: {data_Frame.shape[1]}")

print("\n Principais Features:")
display(data_Frame.columns)

print("\n Principais produtos:")
display(data_Frame['Produto'].value_counts())

print("\nMunicípios por Região:")
municipios_regiao = (
    data_Frame[['Municipio', 'Regiao - Sigla']]
    .drop_duplicates()
    .value_counts('Regiao - Sigla')
)
display(municipios_regiao)

print("\nUnidades de medida por produto:")
unidade_produto = (
    data_Frame[['Produto', 'Unidade de Medida']]
    .drop_duplicates()
    .sort_values(by='Produto')
)
display(unidade_produto)

print("\nPrincipais bandeiras:")
display(data_Frame['Bandeira'].value_counts().head(10))

 ---- VISÃO GERAL DO DATASET ----

Dimensões do dataset:
Linhas: 9889848
Colunas: 16

 Principais Features:

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='object')

 Principais produtos:

Produto
GASOLINA              2804451
ETANOL                2476383
DIESEL S10            2074854
DIESEL                1475800
GASOLINA ADITIVADA     867576
GNV                    181670
Name: count, dtype: int64

Municípios por Região:

Regiao - Sigla
SE    244
NE    144
S     117
N      61
CO     38
Name: count, dtype: int64

Unidades de medida por produto:

                    Produto Unidade de Medida
2                    DIESEL        R$ / litro
4                DIESEL S10        R$ / litro
1                    ETANOL        R$ / litro
0                  GASOLINA        R$ / litro
3        GASOLINA ADITIVADA        R$ / litro
82                      GNV           R$ / m³
3515037                 GNV           R$ / m3
3130447                 NaN               NaN

Principais bandeiras:

Bandeira
BRANCA                          3239682
IPIRANGA                        1833952
RAIZEN                          1507744
PETROBRAS DISTRIBUIDORA S.A.    1459621
VIBRA ENERGIA                    453895
VIBRA                            452995
ALESAT                           237661
SABBÁ                            107301
ATEM' S                           43520
SP                                42369
Name: count, dtype: int64

### 3.2.0 Análises bivariadas por meio de estatísticas descritivas agrupadas sobre os dados brutos

* A análise dos dados brutos em pares de variáveis nos ajuda a entender como elas se relacionam entre si. Ao calcular a média dos preços por região ou município, conseguimos identificar diferenças importantes entre os locais. Isso permite observar padrões geográficos claros e entender como fatores regionais podem influenciar os preços dos combustíveis.

#### 3.2.1. Estatísticas Descritivas Brutas por Regiões Brasileiras

Nesta etapa, analisamos as frequências absoluta (numérica) e relativa (percentual) das regiões brasileiras presentes no dataset, considerando o período de 2015 a 2025.

O objetivo é identificar quais regiões possuem maior representatividade na base de dados, permitindo avaliar possíveis desequilíbrios amostrais (desbalanceamento de classes) entre as regiões. Esse tipo de análise é fundamental, pois a predominância de determinadas regiões pode influenciar os resultados e interpretações das análises subsequentes.

As regiões brasileiras consideradas na base são:

* **N – Norte**
* **NE – Nordeste**
* **SE – Sudeste**
* **S – Sul**
* **CO – Centro-Oeste**

In [ ]:
print("\n FREQUÊNCIA ABSOLUTA DAS REGIÕES \n")
frequencia_regiao_sigla = data_Frame['Regiao - Sigla'].value_counts()
display(frequencia_regiao_sigla)

print(" ")

print("\n FREQUÊNCIA PERCENTUAL DAS REGIÕES \n")
frequencia_regiao_sigla_percentual = (
    data_Frame['Regiao - Sigla']
    .value_counts(normalize=True)
    .round(4) * 100
)
display(frequencia_regiao_sigla_percentual)

 FREQUÊNCIA ABSOLUTA DAS REGIÕES

Regiao - Sigla
SE    4805520
NE    1948525
S     1671048
CO     842951
N      612690
Name: count, dtype: int64

 FREQUÊNCIA PERCENTUAL DAS REGIÕES

Regiao - Sigla
SE    48.64
NE    19.72
S     16.91
CO     8.53
N      6.20
Name: proportion, dtype: float64

#### 3.2.2 Estatísticas Descritivas Brutas das Regiões Brasileiras por Produto

Analisamos as frequências absoluta (numérica) e relativa (percentual) das regiões brasileiras presentes no dataset em relação ao Combustível (Produto), considerando o período de 2015 a 2025.

O objetivo é identificar quais regiões possuem maior representatividade por Produto na base de dados, permitindo avaliar possíveis desequilíbrios amostrais (desbalanceamento de classes) entre as regiões.

---

As regiões brasileiras consideradas na base são:

* **N – Norte**
* **NE – Nordeste**
* **SE – Sudeste**
* **S – Sul**
* **CO – Centro-Oeste**

Os produtos considerados na base são:
* Gasolina Comum
* Gasolina Aditivada
* Etanol
* Diesel
* Diesel S10
* GNV (Gás Natural Veicular)

In [ ]:
print("\n FREQUÊNCIA ABSOLUTA DAS REGIÕES POR PRODUTO \n")
frequencia_regiao_por_produto = (
    data_Frame
    .groupby(['Produto', 'Regiao - Sigla'])
    .size()
    .unstack(fill_value=0)
)
display(frequencia_regiao_por_produto)

print(" ")

print("\n FREQUÊNCIA PERCENTUAL DAS REGIÕES POR PRODUTO \n")
frequencia_regiao_por_produto_percentual = (
    data_Frame
    .groupby(['Produto', 'Regiao - Sigla'])
    .size()
    .unstack(fill_value=0)
    .apply(lambda x: (x / x.sum()) * 100, axis=1)
    .round(2)
)
display(frequencia_regiao_por_produto_percentual)

 FREQUÊNCIA ABSOLUTA DAS REGIÕES POR PRODUTO

Regiao - Sigla          CO       N      NE       S       SE
Produto
DIESEL              147727  127832  250991  268079   681171
DIESEL S10          167006  148752  454854  364531   939711
ETANOL              230593   91795  479263  352163  1322569
GASOLINA            236099  188086  552106  482009  1346151
GASOLINA ADITIVADA   59353   55586  167496  175890   409251
GNV                   2173     639   43815   28376   106667

 FREQUÊNCIA PERCENTUAL DAS REGIÕES POR PRODUTO

Regiao - Sigla         CO     N     NE      S     SE
Produto
DIESEL              10.01  8.66  17.01  18.16  46.16
DIESEL S10           8.05  7.17  21.92  17.57  45.29
ETANOL               9.31  3.71  19.35  14.22  53.41
GASOLINA             8.42  6.71  19.69  17.19  48.00
GASOLINA ADITIVADA   6.84  6.41  19.31  20.27  47.17
GNV                  1.20  0.35  24.12  15.62  58.71

#### 3.2.3. Estatísticas Descritivas Brutas do Valor de Venda por Tipo de Combustível (Produto)

Nesta etapa, analisamos o preço médio de venda dos combustíveis no período de 2015 a 2025, por tipo de produto e por estado brasileiro.

O objetivo é apresentar uma análise descritiva bruta, permitindo observar o comportamento dos preços ao longo do tempo e identificar possíveis variações regionais entre os estados.

É importante destacar que esta análise não considera fatores econômicos externos ou ajustes inflacionários, como o IPCA (Índice Nacional de Preços ao Consumidor Amplo). Dessa forma, os valores apresentados refletem os preços nominais praticados no período, sem correções monetárias.

Essa abordagem fornece uma visão inicial do cenário nacional de preços de combustíveis.

In [ ]:

status_produto_por_combustivel = (
    data_Frame
    .groupby(['Produto', 'Estado - Sigla'])['Valor de Venda']
    .describe()
    .round(2)
)

for produto in status_produto_por_combustivel.index.levels[0]:
    print(f"\n ESTATÍSTICAS PARA {produto} \n")
    display(status_produto_por_combustivel.loc[produto])

 ESTATÍSTICAS PARA DIESEL

                   count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AC               15330.0  4.94  1.50  3.00  3.79  4.39  6.08  8.95
AL               16974.0  3.99  1.40  2.39  3.00  3.47  4.38  8.99
AM               19404.0  4.28  1.40  2.50  3.25  3.67  5.29  9.00
AP                7765.0  4.32  1.28  2.61  3.49  3.85  4.92  7.89
BA               96097.0  4.07  1.41  2.30  3.00  3.48  5.47  8.86
CE               24767.0  3.81  1.15  2.52  3.12  3.37  3.89  8.29
DF               12885.0  4.36  1.39  2.64  3.17  3.78  5.79  8.09
ES               32003.0  3.87  1.25  2.37  2.99  3.32  4.52  8.49
GO               70623.0  4.11  1.33  2.39  3.05  3.51  5.56  8.34
MA               31433.0  4.13  1.41  2.28  3.04  3.49  5.63  8.79
MG              176208.0  4.04  1.32  2.25  3.00  3.50  5.39  8.89
MS               26342.0  4.27  1.33  2.55  3.30  3.65  5.45  8.00
MT               37877.0  4.35  1.28  2.39  3.38  3.84  5.45  8.91
PA               33697.0  4.61  1.54  2.53  3.33  3.88  6.14  8.81
PB               17499.0  4.08  1.41  2.20  2.95  3.40  5.64  8.35
PE               13531.0  3.46  1.11  2.35  2.85  3.00  3.45  8.10
PI               18658.0  4.17  1.37  2.49  3.10  3.59  5.66  8.28
PR               97230.0  3.95  1.38  2.30  2.89  3.29  5.39  8.09
RJ               97845.0  4.00  1.31  2.30  3.00  3.48  5.05  8.78
RN               22632.0  4.12  1.42  2.42  3.05  3.52  5.43  8.24
RO               29240.0  4.45  1.48  2.60  3.30  3.74  6.05  8.71
RR                6329.0  4.75  1.64  2.65  3.25  3.85  6.59  8.52
RS              118641.0  4.27  1.44  2.30  3.00  3.56  5.79  8.28
SC               52208.0  3.96  1.36  2.30  2.92  3.30  5.25  8.12
SE                9400.0  4.00  1.28  2.32  2.98  3.49  5.36  8.09
SP              375115.0  3.95  1.34  2.13  2.93  3.36  5.12  8.52
TO               16067.0  4.29  1.39  2.39  3.05  3.65  5.75  7.89

 ESTATÍSTICAS PARA DIESEL S10

                   count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AC               14662.0  5.10  1.50  3.04  3.96  4.49  6.18  8.98
AL               21316.0  4.48  1.44  2.50  3.22  3.89  5.85  8.99
AM               23907.0  4.83  1.55  2.60  3.54  4.10  6.39  8.99
AP                5955.0  4.90  1.24  2.89  4.02  4.49  6.25  8.09
BA              115474.0  4.40  1.44  2.46  3.23  3.70  5.80  8.99
CE               86931.0  4.43  1.36  2.64  3.31  3.80  5.69  8.89
DF               15518.0  4.55  1.31  2.74  3.50  3.94  5.86  8.76
ES               41188.0  4.34  1.35  2.54  3.20  3.69  5.87  8.49
GO               70102.0  4.56  1.36  2.63  3.40  3.89  5.89  8.51
MA               49308.0  4.44  1.41  2.54  3.22  3.73  5.79  8.99
MG              195637.0  4.44  1.35  2.47  3.28  3.80  5.79  8.99
MS               31247.0  4.33  1.27  2.75  3.42  3.76  5.30  8.15
MT               50139.0  4.55  1.29  2.79  3.60  4.00  5.69  9.15
PA               49602.0  4.67  1.47  2.54  3.44  4.00  6.00  8.91
PB               26005.0  4.43  1.40  2.58  3.20  3.70  5.79  8.51
PE               86107.0  4.21  1.35  2.43  3.05  3.59  5.59  8.30
PI               27999.0  4.43  1.39  2.60  3.30  3.79  5.87  8.88
PR              130232.0  4.22  1.42  2.42  3.04  3.49  5.72  8.59
RJ              139655.0  4.41  1.35  2.10  3.35  3.80  5.80  8.99
RN               24739.0  4.50  1.44  2.69  3.30  3.80  5.96  8.40
RO               27818.0  4.66  1.47  2.80  3.45  3.90  6.25  8.74
RR                7234.0  5.00  1.61  2.80  3.46  4.51  6.70  8.67
RS              141552.0  4.43  1.39  2.46  3.22  3.70  5.89  8.71
SC               92747.0  4.21  1.37  2.47  3.10  3.56  5.59  8.69
SE               16975.0  4.23  1.28  2.59  3.21  3.70  5.50  7.98
SP              563231.0  4.32  1.40  2.10  3.19  3.65  5.69  9.65
TO               19574.0  4.45  1.36  2.47  3.25  3.80  5.80  8.09

 ESTATÍSTICAS PARA ETANOL

                   count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AC                8616.0  4.29  0.97  2.63  3.64  3.99  4.99  7.90
AL               28199.0  3.89  0.91  2.20  3.28  3.65  4.65  7.04
AM               21677.0  3.93  0.89  2.45  3.29  3.59  4.59  6.79
AP                 706.0  4.61  1.01  2.47  3.79  4.94  5.34  6.99
BA              145943.0  3.72  0.92  1.95  3.00  3.48  4.45  7.10
CE               90112.0  4.03  0.96  2.25  3.30  3.70  4.79  7.59
DF               22699.0  3.71  0.89  2.45  3.10  3.49  4.08  7.04
ES               38311.0  3.89  0.86  2.19  3.29  3.69  4.39  7.09
GO              104507.0  3.35  0.82  1.73  2.79  3.08  3.95  6.28
MA               28858.0  4.07  0.90  2.28  3.40  3.85  4.75  7.70
MG              282302.0  3.36  0.84  1.76  2.78  3.12  3.94  7.45
MS               37759.0  3.47  0.79  1.89  3.00  3.35  3.79  6.72
MT               65628.0  3.10  0.83  1.63  2.50  2.80  3.65  6.47
PA               22853.0  4.21  0.91  2.35  3.59  4.00  4.79  7.60
PB               31005.0  3.60  0.88  2.06  2.99  3.39  4.29  6.26
PE               86767.0  3.73  0.94  1.99  3.00  3.48  4.45  7.83
PI               23871.0  3.87  0.88  2.40  3.22  3.60  4.49  6.99
PR              177600.0  3.37  0.90  1.75  2.70  3.05  4.09  7.69
RJ              198564.0  3.91  0.93  2.06  3.29  3.80  4.39  7.98
RN               29181.0  3.94  1.00  2.38  3.20  3.65  4.76  6.99
RO               16408.0  4.06  0.98  2.39  3.39  3.79  4.89  7.45
RR                2235.0  4.20  0.93  2.75  3.59  3.89  5.05  6.88
RS               92622.0  4.04  1.01  2.09  3.49  3.99  4.57  7.90
SC               81941.0  3.78  0.96  2.03  3.10  3.54  4.47  7.45
SE               15327.0  3.85  0.91  2.17  3.20  3.60  4.65  6.53
SP              803392.0  3.12  0.85  1.39  2.50  2.88  3.79  7.90
TO               19300.0  3.92  0.88  2.16  3.35  3.79  4.59  6.88

 ESTATÍSTICAS PARA GASOLINA

                   count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AC               16743.0  5.34  1.25  3.37  4.32  4.95  6.39  8.16
AL               30279.0  4.90  1.16  2.92  3.87  4.68  5.90  8.59
AM               36370.0  5.08  1.33  2.80  3.99  4.65  6.29  8.97
AP               12067.0  4.55  1.00  2.87  3.72  4.15  5.54  7.10
BA              150022.0  4.87  1.18  2.76  3.87  4.57  5.92  8.94
CE               98807.0  4.91  1.12  2.99  3.98  4.60  5.89  8.52
DF               25888.0  4.93  1.16  3.01  3.90  4.65  5.89  8.09
ES               57444.0  4.80  1.16  2.75  3.79  4.50  5.86  7.99
GO              103829.0  4.89  1.12  2.35  3.90  4.66  5.85  8.09
MA               57594.0  4.69  1.12  2.89  3.75  4.40  5.65  8.69
MG              283333.0  4.85  1.11  2.74  3.89  4.76  5.69  8.49
MS               40692.0  4.67  1.14  2.86  3.78  4.30  5.66  7.99
MT               65690.0  4.75  1.08  2.84  3.80  4.50  5.69  8.11
PA               59089.0  5.08  1.14  2.79  4.17  4.79  5.99  8.47
PB               33523.0  4.69  1.14  2.58  3.70  4.40  5.79  7.88
PE               97076.0  4.76  1.17  2.59  3.78  4.42  5.79  8.30
PI               33535.0  4.82  1.20  2.71  3.79  4.60  5.74  8.39
PR              176021.0  4.70  1.16  2.60  3.76  4.30  5.79  8.28
RJ              205959.0  4.99  1.11  2.90  4.00  4.90  5.79  8.99
RN               30895.0  4.85  1.22  2.95  3.86  4.55  5.96  8.09
RO               33573.0  5.04  1.22  3.05  4.00  4.60  6.19  8.71
RR                7913.0  5.03  1.26  3.00  3.87  4.51  6.14  7.41
RS              186734.0  4.87  1.10  2.70  3.96  4.69  5.89  9.08
SC              119254.0  4.61  1.17  2.68  3.66  4.20  5.76  7.89
SE               20375.0  4.83  1.20  2.86  3.75  4.50  5.99  7.99
SP              799415.0  4.58  1.11  2.50  3.60  4.30  5.59  9.29
TO               22331.0  5.06  1.15  2.80  3.99  4.80  6.00  8.75

 ESTATÍSTICAS PARA GASOLINA ADITIVADA

                   count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AC                4885.0  6.76  0.81  4.92  6.28  6.85  7.49  9.69
AL                9528.0  6.20  0.64  4.20  5.79  6.19  6.59  8.59
AM               10982.0  6.41  0.93  3.69  5.79  6.59  6.99  8.94
AP                1112.0  5.85  0.59  3.95  5.45  5.99  6.29  7.15
BA               44266.0  6.32  0.72  3.88  5.89  6.29  6.69  8.99
CE               31569.0  6.31  0.66  4.29  5.90  6.24  6.67  8.69
DF               11551.0  6.00  0.73  3.89  5.50  5.95  6.48  8.29
ES               20222.0  6.17  0.68  3.95  5.79  6.17  6.59  8.88
GO               23083.0  6.18  0.72  4.36  5.73  6.09  6.59  8.22
MA               16046.0  5.98  0.72  3.57  5.50  5.98  6.39  8.78
MG               68216.0  6.17  0.72  4.09  5.69  6.09  6.55  8.89
MS               11217.0  6.09  0.72  4.35  5.65  6.09  6.59  8.08
MT               13502.0  6.11  0.67  4.38  5.69  6.17  6.59  8.39
PA               17218.0  6.38  0.69  4.30  5.97  6.35  6.89  8.57
PB                9468.0  5.97  0.60  4.14  5.60  5.99  6.29  7.89
PE               27152.0  6.15  0.68  4.27  5.69  6.09  6.65  8.50
PI               11095.0  6.22  0.82  4.30  5.69  6.02  6.46  8.78
PR               54688.0  6.12  0.68  3.90  5.69  6.12  6.59  8.59
RJ               71396.0  6.24  0.76  4.44  5.69  6.18  6.59  9.28
RN               11144.0  6.26  0.70  3.52  5.79  6.19  6.69  8.97
RO               10801.0  6.48  0.70  4.55  6.05  6.59  6.99  8.97
RR                3660.0  6.25  0.72  4.12  5.86  6.22  6.97  7.58
RS               78407.0  6.12  0.64  4.13  5.74  6.15  6.49  9.79
SC               42795.0  6.06  0.63  3.85  5.66  6.08  6.49  7.96
SE                7228.0  6.13  0.73  4.43  5.60  6.25  6.62  7.99
SP              249417.0  5.97  0.71  3.46  5.50  5.99  6.39  9.59
TO                6928.0  6.27  0.59  4.54  5.89  6.28  6.65  8.10

 ESTATÍSTICAS PARA GNV

                  count  mean   std   min   25%   50%   75%   max
Estado - Sigla
AL               3564.0  3.82  1.01  1.59  2.90  4.20  4.69  5.79
AM                614.0  3.81  0.93  2.00  3.15  3.99  4.49  5.49
AP                  8.0  2.90  0.45  2.74  2.74  2.74  2.74  4.02
BA               9486.0  3.25  0.90  1.59  2.44  3.09  4.07  6.22
CE               7512.0  3.84  1.01  1.97  2.94  3.67  4.88  6.28
DF                 62.0  6.18  1.11  3.24  6.19  6.69  6.82  7.09
ES               6326.0  3.78  1.15  1.69  2.69  4.09  4.89  6.09
GO                 96.0  2.79  0.46  2.00  2.69  2.79  2.80  6.37
MA                 19.0  3.84  0.81  2.90  3.25  3.50  4.36  5.46
MG               4874.0  4.07  1.10  1.80  3.13  4.55  4.99  6.09
MS               1210.0  3.32  1.02  1.99  2.38  2.94  4.39  5.55
MT                805.0  3.05  0.57  1.99  2.70  2.90  3.54  7.99
PA                  7.0  3.87  1.35  2.00  3.00  4.43  4.58  5.50
PB               4866.0  3.79  1.12  1.76  2.69  3.72  4.85  6.25
PE               9923.0  3.30  1.00  1.74  2.20  3.39  4.35  5.77
PI                  6.0  3.33  0.36  2.99  3.04  3.24  3.63  3.79
PR               2999.0  3.85  1.30  1.40  2.59  3.48  4.99  6.89
RJ              66762.0  3.59  1.22  1.38  2.40  3.50  4.59  7.43
RN               5462.0  3.47  1.05  1.92  2.49  3.46  4.49  6.19
RO                  3.0  3.82  0.80  3.00  3.43  3.87  4.23  4.59
RR                  1.0  4.99   NaN  4.99  4.99  4.99  4.99  4.99
RS              11407.0  3.86  1.19  2.00  2.70  3.60  4.79  6.89
SC              13970.0  3.58  1.37  1.70  2.20  3.00  4.99  6.89
SE               2977.0  3.58  1.15  1.80  2.38  3.68  4.87  5.49
SP              28705.0  3.41  1.21  1.50  2.23  3.18  4.50  6.99
TO                  6.0  3.25  0.26  3.00  3.01  3.26  3.49  3.50

#### 3.2.4. Estatísticas Descritivas Brutas por Tipo de Combustível (Produto) com Ranking dos Municípios Mais Caros e Mais Baratos

Nesta etapa, analisamos o preço médio bruto de venda dos combustíveis nos municípios brasileiros, considerando o período de 2015 a 2025.

A análise é segmentada por tipo de combustível (produto) e tem como objetivo identificar os 10 municípios com maiores preços médios e os 10 com menores preços médios, permitindo uma comparação média e direta entre diferentes localidades dentro de cada categoria de combustível.

Os valores apresentados correspondem a médias históricas do período analisado, caracterizando uma análise descritiva bruta, sem a aplicação de ajustes inflacionários ou controle por variáveis econômicas, como o IPCA.

Essa abordagem possibilita evidenciar disparidades regionais e identificar padrões de precificação entre municípios brasileiros, servindo como base para análises mais aprofundadas.

In [ ]:
print("\n MUNICÍPIOS MAIS CAROS E MAIS BARATOS POR PRODUTO (média entre 2015 a 2025) \n")

media_municipio_por_produto = (
    data_Frame
    .groupby(['Produto', 'Estado - Sigla', 'Municipio'])['Valor de Venda']
    .mean()
    .round(2)
    .reset_index()
)

for produto in data_Frame['Produto'].unique():

    print(f"\n------ {produto} ------ \n")

    dados_produto_por_municipio = media_municipio_por_produto[
        media_municipio_por_produto['Produto'] == produto
    ]

    dados_ordenados = dados_produto_por_municipio.sort_values(by='Valor de Venda', ascending=False)

    print("Top 10 municípios MAIS CAROS:\n")
    display(dados_ordenados.head(10))

    print("\nTop 10 municípios MAIS BARATOS:\n")
    display(dados_ordenados.tail(10))

 MUNICÍPIOS MAIS CAROS E MAIS BARATOS POR PRODUTO (média entre 2015 a 2025)


------ GASOLINA ------

Top 10 municípios MAIS CAROS:

       Produto Estado - Sigla        Municipio  Valor de Venda
2238  GASOLINA             SE       JAPARATUBA            6.85
2109  GASOLINA             RJ         MESQUITA            6.74
2186  GASOLINA             RS   ROSARIO DO SUL            6.20
1810  GASOLINA             BA           GAVIAO            5.99
1786  GASOLINA             AM        PARINTINS            5.83
1767  GASOLINA             AC  CRUZEIRO DO SUL            5.77
1999  GASOLINA             PA         ALTAMIRA            5.74
1774  GASOLINA             AL  DELMIRO GOUVEIA            5.58
1834  GASOLINA             BA        VERA CRUZ            5.57
2158  GASOLINA             RS             BAGE            5.56

Top 10 municípios MAIS BARATOS:

       Produto Estado - Sigla            Municipio  Valor de Venda
2170  GASOLINA             RS              ESTRELA            3.20
2031  GASOLINA             PE         BOM CONSELHO            3.20
2226  GASOLINA             SC          PORTO UNIAO            3.20
2279  GASOLINA             SP      FRANCO DA ROCHA            3.20
2047  GASOLINA             PE     SAO BENTO DO UNA            3.18
2024  GASOLINA             PB                 SAPE            3.17
2021  GASOLINA             PB           MAMANGUAPE            3.15
2059  GASOLINA             PR  ALMIRANTE TAMANDARE            3.15
2278  GASOLINA             SP     FRANCISCO MORATO            3.14
2225  GASOLINA             SC          PINHALZINHO            3.11

------ ETANOL ------

Top 10 municípios MAIS CAROS:

     Produto Estado - Sigla              Municipio  Valor de Venda
1406  ETANOL             PA               ALENQUER            6.23
1636  ETANOL             SE             JAPARATUBA            5.45
1515  ETANOL             RJ               MESQUITA            5.44
1204  ETANOL             AP                SANTANA            5.33
1186  ETANOL             AC        CRUZEIRO DO SUL            5.12
1407  ETANOL             PA               ALTAMIRA            4.92
1562  ETANOL             RS                   BAGE            4.72
1421  ETANOL             PA               SANTAREM            4.64
1593  ETANOL             RS  SANTANA DO LIVRAMENTO            4.54
1203  ETANOL             AP                 MACAPA            4.52

Top 10 municípios MAIS BARATOS:

     Produto Estado - Sigla                  Municipio  Valor de Venda
1340  ETANOL             MG                    IBIRITE            2.27
1487  ETANOL             PR              NOVA LONDRINA            2.21
1644  ETANOL             SP                      APIAI            2.17
1674  ETANOL             SP      FERRAZ DE VASCONCELOS            2.16
1401  ETANOL             MT  SANTO ANTONIO DO LEVERGER            2.16
1625  ETANOL             SC                PINHALZINHO            2.14
1465  ETANOL             PR        ALMIRANTE TAMANDARE            2.11
1677  ETANOL             SP            FRANCO DA ROCHA            2.08
1399  ETANOL             MT                 DIAMANTINO            2.07
1676  ETANOL             SP           FRANCISCO MORATO            2.01

------ DIESEL ------

Top 10 municípios MAIS CAROS:

    Produto Estado - Sigla                Municipio  Valor de Venda
260  DIESEL             PE  CABO DE SANTO AGOSTINHO            6.42
230  DIESEL             PA                    BELEM            6.31
21   DIESEL             AM                     TEFE            6.24
81   DIESEL             CE                MARACANAU            5.97
268  DIESEL             PE                   OLINDA            5.93
74   DIESEL             CE                FORTALEZA            5.85
71   DIESEL             CE                  CAUCAIA            5.71
42   DIESEL             BA                   GAVIAO            5.70
229  DIESEL             PA               ANANINDEUA            5.56
271  DIESEL             PE                   RECIFE            5.54

Top 10 municípios MAIS BARATOS:

    Produto Estado - Sigla            Municipio  Valor de Venda
285  DIESEL             PR  ALMIRANTE TAMANDARE            2.66
129  DIESEL             MA              FORTUNA            2.66
499  DIESEL             SP     FRANCISCO MORATO            2.66
395  DIESEL             RS              ESTRELA            2.65
467  DIESEL             SP                APIAI            2.64
307  DIESEL             PR        NOVA LONDRINA            2.63
66   DIESEL             BA            VERA CRUZ            2.63
449  DIESEL             SC          PINHALZINHO            2.62
39   DIESEL             BA           CORRENTINA            2.58
36   DIESEL             BA              CANDEAL            2.58

------ GASOLINA ADITIVADA ------

Top 10 municípios MAIS CAROS:

,Produto,Estado - Sigla,Municipio,Valor de Venda
2379,GASOLINA ADITIVADA,AM,PARINTINS,7.60
2369,GASOLINA ADITIVADA,AC,CRUZEIRO DO SUL,7.51
2380,GASOLINA ADITIVADA,AM,TEFE,7.28
2657,GASOLINA ADITIVADA,RS,BAGE,6.98
2553,GASOLINA ADITIVADA,PA,XINGUARA,6.97
2372,GASOLINA ADITIVADA,AL,DELMIRO GOUVEIA,6.92
2404,GASOLINA ADITIVADA,BA,PORTO SEGURO,6.88
2525,GASOLINA ADITIVADA,MS,CORUMBA,6.86
2635,GASOLINA ADITIVADA,RJ,SAO FRANCISCO DE ITABAPOANA,6.82
2651,GASOLINA ADITIVADA,RO,PIMENTA BUENO,6.81

Top 10 municípios MAIS BARATOS:

                 Produto Estado - Sigla              Municipio  Valor de Venda
2728  GASOLINA ADITIVADA             SP                  BAURU            5.72
2733  GASOLINA ADITIVADA             SP               CACAPAVA            5.72
2464  GASOLINA ADITIVADA             MA    SAO JOSE DE RIBAMAR            5.70
2814  GASOLINA ADITIVADA             SP                 SUZANO            5.68
2798  GASOLINA ADITIVADA             SP  SANTA BARBARA D'OESTE            5.65
2763  GASOLINA ADITIVADA             SP                JACAREI            5.65
2807  GASOLINA ADITIVADA             SP    SAO JOSE DOS CAMPOS            5.62
2817  GASOLINA ADITIVADA             SP                TAUBATE            5.59
2738  GASOLINA ADITIVADA             SP             COSMOPOLIS            5.58
2786  GASOLINA ADITIVADA             SP        PINDAMONHANGABA            5.54

------ DIESEL S10 ------

Top 10 municípios MAIS CAROS:

         Produto Estado - Sigla          Municipio  Valor de Venda
928   DIESEL S10             RJ           MESQUITA            6.35
607   DIESEL S10             AM          PARINTINS            6.13
1055  DIESEL S10             SE         JAPARATUBA            6.05
817   DIESEL S10             PA           ALENQUER            5.84
630   DIESEL S10             BA             GAVIAO            5.80
590   DIESEL S10             AC    CRUZEIRO DO SUL            5.79
655   DIESEL S10             BA          VERA CRUZ            5.40
615   DIESEL S10             AP            SANTANA            5.36
818   DIESEL S10             PA           ALTAMIRA            5.36
670   DIESEL S10             CE  LIMOEIRO DO NORTE            5.33

Top 10 municípios MAIS BARATOS:

         Produto Estado - Sigla                     Municipio  Valor de Venda
878   DIESEL S10             PR           ALMIRANTE TAMANDARE            2.79
933   DIESEL S10             RJ                PARAIBA DO SUL            2.78
900   DIESEL S10             PR                 NOVA LONDRINA            2.78
627   DIESEL S10             BA                    CORRENTINA            2.77
728   DIESEL S10             MA  SAO RAIMUNDO DAS MANGABEIRAS            2.77
850   DIESEL S10             PE                  BOM CONSELHO            2.76
719   DIESEL S10             MA                       FORTUNA            2.76
1095  DIESEL S10             SP              FRANCISCO MORATO            2.76
625   DIESEL S10             BA                     CANSANCAO            2.76
866   DIESEL S10             PE              SAO BENTO DO UNA            2.75

------ GNV ------

Top 10 municípios MAIS CAROS:

     Produto Estado - Sigla               Municipio  Valor de Venda
2878     GNV             GO                MINEIROS            6.37
2860     GNV             CE                 QUIXADA            6.26
2992     GNV             RJ  SANTO ANTONIO DE PADUA            6.21
2861     GNV             DF                BRASILIA            6.18
2968     GNV             RJ          ANGRA DOS REIS            5.70
2853     GNV             BA    VITORIA DA CONQUISTA            5.67
2985     GNV             RJ           NOVA FRIBURGO            5.65
3025     GNV             RS                 PELOTAS            5.55
3059     GNV             SP                  AMPARO            5.54
2925     GNV             PA                ALTAMIRA            5.50

Top 10 municípios MAIS BARATOS:

     Produto Estado - Sigla             Municipio  Valor de Venda
3003     GNV             RN         CURRAIS NOVOS            2.08
3085     GNV             SP               ITAPEVI            2.05
2932     GNV             PB            MAMANGUAPE            2.03
2966     GNV             PR                TOLEDO            2.00
2927     GNV             PA                CAMETA            2.00
2874     GNV             GO          CALDAS NOVAS            2.00
2935     GNV             PB                  SAPE            1.99
2840     GNV             BA      AMELIA RODRIGUES            1.96
2843     GNV             BA  CONCEICAO DO JACUIPE            1.95
2988     GNV             RJ             QUEIMADOS            1.93

------ nan ------

Top 10 municípios MAIS CAROS:

Empty DataFrame
Columns: [Produto, Estado - Sigla, Municipio, Valor de Venda]
Index: []

Top 10 municípios MAIS BARATOS:

Empty DataFrame
Columns: [Produto, Estado - Sigla, Municipio, Valor de Venda]
Index: []

#### 3.2.5. Evolução Bruta de Preços dos Combustíveis ao Longo do Tempo

Analisamos a evolução dos preços de venda dos combustíveis ao longo dos anos, considerando o período de 2015 a 2025.

A análise evidencia a tendência geral dos preços no Brasil, permitindo identificar períodos de aumento ou estabilidade ao longo do tempo. Como se trata de uma análise bruta, os valores não foram ajustados por inflação, refletindo os preços nominais observados em cada período.

In [ ]:
print("\n ---- EVOLUÇÃO DE PREÇOS POR ANO ---- \n")

data_Frame['Data da Coleta'] = pd.to_datetime(data_Frame['Data da Coleta'], errors='coerce')

data_Frame['Ano'] = data_Frame['Data da Coleta'].dt.year

for produto in sorted(data_Frame['Produto'].dropna().unique()):

    print(f"\n---- {produto} ----\n")

    data_frame_produto = data_Frame[data_Frame['Produto'] == produto]

    tabela_evolucao_precos_por_ano_produto = (
        data_frame_produto
        .groupby('Ano')['Valor de Venda']
        .agg(
            Media='mean',
            Mediana='median',
            Min='min',
            Max='max'
        )
        .round(2)
        .sort_index()
    )

    display(tabela_evolucao_precos_por_ano_produto)

 ---- EVOLUÇÃO DE PREÇOS POR ANO ----


---- DIESEL ----

        Media  Mediana   Min   Max
Ano
2015.0   2.81     2.80  2.20  3.98
2016.0   3.02     2.99  2.46  3.98
2017.0   3.09     3.08  2.39  4.47
2018.0   3.50     3.49  2.83  4.95
2019.0   3.59     3.59  2.89  4.99
2020.0   3.43     3.42  2.49  5.00
2021.0   4.66     4.60  3.20  6.70
2022.0   6.57     6.67  4.07  8.99
2023.0   5.76     5.85  3.97  7.99
2024.0   5.97     5.89  4.69  8.19
2025.0   6.17     6.09  5.29  8.33

---- DIESEL S10 ----

        Media  Mediana   Min   Max
Ano
2015.0   2.96     2.95  2.10  4.02
2016.0   3.15     3.12  2.49  4.25
2017.0   3.21     3.20  2.45  4.50
2018.0   3.59     3.58  2.89  5.09
2019.0   3.68     3.69  2.98  5.09
2020.0   3.52     3.50  2.53  5.15
2021.0   4.71     4.67  3.24  6.80
2022.0   6.66     6.79  3.59  9.00
2023.0   5.86     5.99  4.27  9.00
2024.0   6.03     5.99  4.99  8.99
2025.0   6.22     6.19  4.73  9.29

---- ETANOL ----

        Media  Mediana   Min   Max
Ano
2015.0   2.38     2.39  1.39  3.80
2016.0   2.86     2.83  1.60  4.48
2017.0   2.90     2.89  1.70  4.48
2018.0   3.13     3.09  1.95  4.95
2019.0   3.16     3.08  2.10  5.47
2020.0   3.18     3.18  1.80  5.15
2021.0   4.61     4.59  2.48  7.90
2022.0   4.85     4.88  2.49  7.90
2023.0   4.03     3.99  2.78  6.73
2024.0   4.05     3.99  2.69  6.60
2025.0   4.45     4.39  3.19  7.44

---- GASOLINA ----

        Media  Mediana   Min   Max
Ano
2015.0   3.35     3.35  2.35  4.80
2016.0   3.72     3.70  3.01  4.90
2017.0   3.76     3.77  2.80  5.20
2018.0   4.45     4.43  3.37  6.29
2019.0   4.42     4.40  3.45  6.29
2020.0   4.29     4.30  2.87  5.90
2021.0   5.82     5.80  3.10  8.00
2022.0   6.29     6.45  4.15  8.99
2023.0   5.54     5.49  4.09  7.79
2024.0   5.92     5.89  4.58  7.99
2025.0   6.25     6.19  4.99  9.29

---- GASOLINA ADITIVADA ----

        Media  Mediana   Min   Max
Ano
2020.0   4.57     4.58  3.69  6.00
2021.0   5.97     5.96  3.46  8.99
2022.0   6.44     6.59  4.27  9.28
2023.0   5.73     5.69  3.89  8.69
2024.0   6.10     6.09  4.69  9.79
2025.0   6.45     6.41  5.19  9.59

---- GNV ----

        Media  Mediana   Min   Max
Ano
2015.0   2.03     2.00  1.38  3.09
2016.0   2.26     2.20  1.70  3.40
2017.0   2.35     2.30  1.70  3.20
2018.0   2.72     2.70  1.76  4.10
2019.0   3.21     3.19  2.00  4.32
2020.0   3.17     3.10  2.00  4.15
2021.0   3.86     3.90  2.40  6.20
2022.0   5.03     4.99  3.17  7.43
2023.0   4.66     4.59  3.15  6.71
2024.0   4.77     4.69  3.54  6.89
2025.0   4.75     4.69  3.79  6.49

#### 3.2.6. Evolução Bruta de Preços ao Longo do Tempo e Por Região

Complementando a análise temporal, foi realizada a segmentação da média de preços por ano e por região brasileira.

Essa abordagem permite identificar diferenças regionais na evolução dos preços, evidenciando possíveis disparidades entre as regiões ao longo do tempo.

In [ ]:
print("\n ---- EVOLUÇÃO DE PREÇOS POR ANO, REGIÃO E PRODUTO ---- \n")

for produto in data_Frame['Produto'].unique():

    print(f"\n ⚠️ {produto} ⚠️ \n")

    dados_produto = data_Frame[data_Frame['Produto'] == produto]

    grupo_por_produto_regiao_e_ano = dados_produto.groupby(['Ano', 'Regiao - Sigla'])['Valor de Venda']

    media = grupo_por_produto_regiao_e_ano.mean().round(2).unstack()
    mediana = grupo_por_produto_regiao_e_ano.median().round(2).unstack()
    minimo = grupo_por_produto_regiao_e_ano.min().round(2).unstack()
    maximo = grupo_por_produto_regiao_e_ano.max().round(2).unstack()

    print("\n--- MÉDIA ---")
    display(media)

    print("\n--- MEDIANA ---")
    display(mediana)

    print("\n--- MÍNIMO ---")
    display(minimo)

    print("\n--- MÁXIMO ---")
    display(maximo)

 ---- EVOLUÇÃO DE PREÇOS POR ANO, REGIÃO E PRODUTO ----


 ⚠️ GASOLINA ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.43  3.61  3.38  3.32  3.30
2016.0          3.74  3.98  3.78  3.73  3.66
2017.0          3.80  4.02  3.76  3.76  3.72
2018.0          4.52  4.59  4.43  4.39  4.44
2019.0          4.45  4.53  4.49  4.31  4.41
2020.0          4.35  4.40  4.34  4.20  4.27
2021.0          6.01  5.86  5.89  5.81  5.76
2022.0          6.27  6.43  6.52  6.18  6.21
2023.0          5.49  5.92  5.68  5.58  5.43
2024.0          5.91  6.33  6.00  5.97  5.80
2025.0          6.29  6.72  6.29  6.33  6.12

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.45  3.59  3.39  3.30  3.29
2016.0          3.78  3.97  3.80  3.71  3.64
2017.0          3.80  3.99  3.80  3.78  3.70
2018.0          4.52  4.59  4.46  4.38  4.40
2019.0          4.47  4.58  4.50  4.29  4.38
2020.0          4.39  4.49  4.39  4.20  4.28
2021.0          5.99  5.89  5.89  5.80  5.70
2022.0          6.45  6.67  6.68  6.39  6.29
2023.0          5.49  5.96  5.68  5.59  5.39
2024.0          5.92  6.29  5.99  5.99  5.79
2025.0          6.34  6.79  6.32  6.29  6.09

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.35  2.79  2.59  2.69  2.57
2016.0          3.09  3.19  3.09  3.08  3.01
2017.0          3.06  2.98  2.98  2.95  2.80
2018.0          3.40  3.55  3.47  3.50  3.37
2019.0          3.70  3.47  3.69  3.60  3.45
2020.0          3.28  2.87  3.35  3.10  2.92
2021.0          4.30  3.82  3.99  4.04  3.10
2022.0          4.17  4.37  4.33  4.36  4.15
2023.0          4.44  4.37  4.15  4.09  4.09
2024.0          4.79  5.03  4.75  4.99  4.58
2025.0          5.19  5.37  5.19  5.19  4.99

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          4.10  4.80  4.30  4.00  4.72
2016.0          4.30  4.65  4.63  4.48  4.90
2017.0          4.75  5.20  4.79  4.80  5.00
2018.0          5.39  6.29  5.40  5.40  5.80
2019.0          5.20  6.29  5.79  5.40  5.99
2020.0          5.25  5.69  5.46  5.50  5.90
2021.0          7.50  7.60  7.49  8.00  8.00
2022.0          7.99  8.19  8.77  8.28  8.99
2023.0          6.89  7.70  6.98  6.94  7.79
2024.0          7.09  7.99  7.39  7.33  7.99
2025.0          7.19  8.39  7.59  7.49  9.29

 ⚠️ ETANOL ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.35  2.82  2.57  2.47  2.26
2016.0          2.78  3.40  3.10  3.08  2.68
2017.0          2.79  3.51  3.13  3.14  2.72
2018.0          3.01  3.72  3.43  3.37  2.95
2019.0          2.97  3.74  3.53  3.36  2.97
2020.0          3.04  3.71  3.47  3.41  3.01
2021.0          4.50  4.95  4.91  4.88  4.44
2022.0          4.53  5.47  5.35  5.22  4.59
2023.0          3.76  4.67  4.43  4.32  3.82
2024.0          3.82  4.58  4.48  4.24  3.84
2025.0          4.34  5.08  4.84  4.63  4.23

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.35  2.79  2.58  2.50  2.20
2016.0          2.77  3.40  3.10  3.00  2.65
2017.0          2.79  3.50  3.15  3.00  2.69
2018.0          2.99  3.69  3.46  3.25  2.90
2019.0          2.98  3.75  3.50  3.20  2.86
2020.0          3.05  3.74  3.49  3.35  2.98
2021.0          4.50  4.99  5.00  4.87  4.36
2022.0          4.65  5.59  5.46  5.09  4.59
2023.0          3.79  4.59  4.42  4.29  3.79
2024.0          3.88  4.59  4.49  4.19  3.80
2025.0          4.34  4.99  4.89  4.59  4.19

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          1.67  2.16  1.95  1.79  1.39
2016.0          2.17  2.79  2.38  2.15  1.60
2017.0          1.85  2.69  2.42  2.15  1.70
2018.0          2.17  2.99  2.62  2.17  1.95
2019.0          2.12  3.07  2.72  2.42  2.10
2020.0          2.17  2.80  2.55  2.16  1.80
2021.0          2.95  3.26  3.30  2.97  2.48
2022.0          2.69  3.59  3.19  3.19  2.49
2023.0          2.79  3.75  3.39  3.09  2.78
2024.0          2.73  3.45  3.19  3.09  2.69
2025.0          3.45  4.10  3.72  3.45  3.19

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.13  3.80  3.50  3.60  3.75
2016.0          3.56  4.14  3.95  4.48  4.00
2017.0          3.70  4.30  4.30  4.48  4.05
2018.0          4.00  4.80  4.30  4.95  4.50
2019.0          4.00  5.47  4.50  5.00  5.00
2020.0          4.17  4.86  4.79  5.15  4.94
2021.0          6.80  7.60  6.70  7.90  7.74
2022.0          6.72  7.50  7.83  7.89  7.90
2023.0          5.60  6.60  6.50  6.73  6.59
2024.0          5.89  6.60  6.01  6.16  5.99
2025.0          5.29  7.44  6.49  6.42  6.39

 ⚠️ DIESEL ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.95  3.07  2.80  2.75  2.76
2016.0          3.14  3.32  3.04  2.91  2.97
2017.0          3.27  3.38  3.08  2.96  3.06
2018.0          3.67  3.76  3.53  3.35  3.46
2019.0          3.72  3.92  3.67  3.44  3.54
2020.0          3.54  3.75  3.47  3.29  3.38
2021.0          4.84  4.97  4.77  4.51  4.60
2022.0          6.62  6.92  6.82  6.39  6.46
2023.0          5.77  6.18  5.80  5.67  5.69
2024.0          5.93  6.43  5.98  5.94  5.89
2025.0          6.15  6.64  6.14  6.14  6.09

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.90  3.05  2.79  2.76  2.76
2016.0          3.12  3.29  3.05  2.90  2.97
2017.0          3.24  3.35  3.09  2.95  3.05
2018.0          3.65  3.71  3.50  3.32  3.45
2019.0          3.70  3.88  3.67  3.44  3.54
2020.0          3.56  3.75  3.49  3.30  3.40
2021.0          4.80  4.91  4.74  4.45  4.56
2022.0          6.74  6.99  6.95  6.49  6.59
2023.0          5.89  6.28  5.89  5.79  5.79
2024.0          5.89  6.35  5.94  5.89  5.87
2025.0          6.14  6.59  6.09  6.13  6.03

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.39  2.48  2.28  2.30  2.20
2016.0          2.73  2.60  2.63  2.50  2.46
2017.0          2.73  2.50  2.49  2.39  2.46
2018.0          3.15  3.00  2.90  2.83  2.89
2019.0          3.02  3.14  2.99  2.89  2.90
2020.0          2.59  2.55  2.64  2.49  2.55
2021.0          3.54  3.29  3.29  3.20  3.20
2022.0          4.99  4.62  4.07  4.61  4.79
2023.0          4.29  4.12  4.39  4.29  3.97
2024.0          5.19  4.69  5.09  5.04  5.13
2025.0          5.33  5.39  5.29  5.29  5.29

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.59  3.98  3.49  3.51  3.49
2016.0          3.62  3.98  3.49  3.45  3.63
2017.0          4.08  4.47  3.98  4.29  4.00
2018.0          4.53  4.95  4.41  4.78  4.71
2019.0          4.54  4.99  4.65  4.49  4.99
2020.0          4.57  4.99  4.49  4.31  5.00
2021.0          6.47  6.70  6.24  6.16  6.55
2022.0          8.34  8.99  8.79  8.10  8.52
2023.0          7.55  7.99  7.67  7.59  7.77
2024.0          7.49  8.19  6.99  7.59  7.89
2025.0          7.74  8.33  7.29  7.59  8.19

 ⚠️ GASOLINA ADITIVADA ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2020.0          4.70  4.57  4.62  4.50  4.55
2021.0          6.10  6.00  6.07  5.95  5.92
2022.0          6.39  6.56  6.67  6.31  6.39
2023.0          5.63  6.08  5.82  5.73  5.65
2024.0          6.06  6.51  6.13  6.12  6.04
2025.0          6.45  6.90  6.43  6.48  6.37

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2020.0          4.68  4.59  4.65  4.47  4.50
2021.0          6.06  6.03  6.00  5.95  5.90
2022.0          6.59  6.79  6.85  6.49  6.49
2023.0          5.65  6.09  5.82  5.76  5.62
2024.0          5.99  6.47  6.14  6.09  5.99
2025.0          6.48  6.98  6.47  6.49  6.34

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2020.0          3.95  3.69  3.88  3.90  3.79
2021.0          4.39  4.05  4.29  4.06  3.46
2022.0          4.36  4.57  4.36  4.39  4.27
2023.0          3.89  4.56  4.48  4.49  4.26
2024.0          4.85  5.16  4.94  5.06  4.69
2025.0          5.45  5.65  5.22  5.55  5.19

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2020.0          5.29  5.31  5.21  5.59  6.00
2021.0          7.83  7.70  8.99  8.10  8.50
2022.0          8.19  8.35  8.82  8.59  9.28
2023.0          6.99  7.57  7.29  8.49  8.69
2024.0          7.19  8.09  7.37  9.79  8.89
2025.0          8.39  8.72  8.49  7.69  9.59

 ⚠️ DIESEL S10 ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.14  3.17  2.95  2.92  2.92
2016.0          3.34  3.41  3.16  3.06  3.11
2017.0          3.45  3.45  3.17  3.09  3.19
2018.0          3.79  3.83  3.59  3.46  3.56
2019.0          3.84  3.97  3.72  3.55  3.65
2020.0          3.64  3.80  3.52  3.39  3.50
2021.0          4.90  4.98  4.77  4.55  4.66
2022.0          6.76  6.97  6.81  6.49  6.59
2023.0          5.89  6.24  5.83  5.80  5.83
2024.0          6.00  6.40  5.97  6.02  6.01
2025.0          6.20  6.59  6.13  6.23  6.19

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.15  3.15  2.95  2.91  2.90
2016.0          3.33  3.38  3.17  3.06  3.10
2017.0          3.46  3.40  3.19  3.09  3.20
2018.0          3.79  3.76  3.59  3.44  3.55
2019.0          3.82  3.94  3.70  3.55  3.65
2020.0          3.67  3.80  3.55  3.40  3.50
2021.0          4.87  4.90  4.71  4.50  4.60
2022.0          6.89  6.99  6.98  6.59  6.69
2023.0          5.99  6.29  5.95  5.89  5.97
2024.0          5.97  6.37  5.94  5.99  5.99
2025.0          6.19  6.49  6.09  6.19  6.09

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.67  2.54  2.43  2.42  2.10
2016.0          2.94  2.82  2.68  2.49  2.60
2017.0          2.89  2.60  2.59  2.45  2.63
2018.0          3.20  3.09  3.00  2.89  2.94
2019.0          3.20  3.15  3.15  2.98  3.00
2020.0          2.63  2.60  2.65  2.53  2.58
2021.0          3.57  3.58  3.34  3.24  3.26
2022.0          3.59  4.99  4.96  4.36  4.54
2023.0          4.49  4.43  4.34  4.45  4.27
2024.0          5.19  5.11  5.09  5.29  4.99
2025.0          5.33  5.23  4.73  5.29  5.09

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          3.72  4.02  3.80  3.59  3.96
2016.0          3.77  4.25  3.80  3.66  4.00
2017.0          4.19  4.50  4.20  4.40  4.10
2018.0          5.08  5.09  4.52  4.93  4.80
2019.0          4.64  5.07  4.70  4.68  5.09
2020.0          4.67  5.07  4.85  4.68  5.15
2021.0          6.64  6.80  6.47  6.26  6.65
2022.0          8.51  8.99  8.99  8.71  9.00
2023.0          8.04  8.91  8.88  7.75  9.00
2024.0          7.58  8.89  8.74  7.26  8.99
2025.0          8.87  8.39  7.44  7.73  9.29

 ⚠️ GNV ⚠️


--- MÉDIA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.32  2.28  2.12  2.20  1.93
2016.0          2.49  2.82  2.37  2.39  2.15
2017.0          2.48  2.93  2.48  2.34  2.29
2018.0          2.70  3.10  2.94  2.63  2.65
2019.0          2.97  3.17  3.37  3.17  3.16
2020.0          3.11  3.37  3.26  3.26  3.11
2021.0          3.57  3.80  3.85  4.06  3.80
2022.0          4.35  4.21  4.61  5.66  5.07
2023.0          4.27  4.42  4.35  5.20  4.64
2024.0          4.08  4.70  4.74  4.86  4.77
2025.0          4.36  4.98  4.74  4.95  4.71

--- MEDIANA ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.20  2.30  2.09  2.20  1.90
2016.0          2.40  2.85  2.39  2.30  2.10
2017.0          2.40  2.85  2.46  2.40  2.29
2018.0          2.70  3.15  2.98  2.78  2.60
2019.0          2.94  3.17  3.49  3.20  3.10
2020.0          3.19  3.29  3.29  3.20  3.08
2021.0          3.50  3.79  3.79  4.20  3.90
2022.0          4.49  4.38  4.54  5.79  4.99
2023.0          3.54  4.49  4.39  5.19  4.58
2024.0          4.19  4.59  4.69  4.89  4.69
2025.0          4.05  4.99  4.72  4.97  4.59

--- MÍNIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          1.99  2.00  1.74  1.40  1.38
2016.0          1.99  2.55  1.80  1.89  1.70
2017.0          2.30  2.79  1.78  1.70  1.75
2018.0          2.40  2.85  2.29  1.76  1.99
2019.0          2.68  3.00  2.69  2.49  2.00
2020.0          2.00  3.29  2.45  2.75  2.35
2021.0          2.70  3.49  2.70  2.74  2.40
2022.0          3.17  3.99  3.49  4.00  3.66
2023.0          3.19  4.19  3.15  3.99  3.56
2024.0          3.54  3.99  3.74  3.99  3.58
2025.0          3.92  3.99  3.89  4.29  3.79

--- MÁXIMO ---

Regiao - Sigla    CO     N    NE     S    SE
Ano
2015.0          2.80  2.30  2.95  3.09  2.99
2016.0          2.99  3.15  3.06  3.29  3.40
2017.0          2.70  3.20  3.04  3.10  3.10
2018.0          3.89  3.19  3.79  3.65  4.10
2019.0          4.09  3.50  4.06  4.15  4.32
2020.0          3.80  4.00  4.09  4.15  4.10
2021.0          4.59  4.59  5.19  5.10  6.20
2022.0          7.09  4.39  5.89  6.89  7.43
2023.0          6.69  4.99  6.28  6.59  6.71
2024.0          6.69  4.99  6.28  5.94  6.89
2025.0          4.79  5.49  6.09  6.14  6.49

 ⚠️ nan ⚠️


--- MÉDIA ---

Empty DataFrame
Columns: []
Index: []

--- MEDIANA ---

Empty DataFrame
Columns: []
Index: []

--- MÍNIMO ---

Empty DataFrame
Columns: []
Index: []

--- MÁXIMO ---

Empty DataFrame
Columns: []
Index: []

### 3.3.0. Análise de Correlação entre os Valores de Venda e o Poder de Compra (IPCA)

Nesta etapa, investigamos a relação entre os valores de venda dos combustíveis ao longo dos anos e o poder de compra da população brasileira, representado pelo IPCA (Índice Nacional de Preços ao Consumidor Amplo).

O objetivo é verificar a existência de correlação entre a evolução dos preços dos combustíveis e a inflação oficial do país, buscando compreender se o aumento nos preços acompanha, supera ou diverge da variação inflacionária no período analisado (2015 a 2025).

A análise de correlação permite identificar o grau de associação entre essas variáveis, indicando se existe uma relação:

positiva (os preços sobem junto com a inflação),
negativa (movimentos inversos),
ou fraca/inexistente (sem relação significativa).

É importante destacar que a correlação não implica causalidade, ou seja, mesmo que haja associação entre as variáveis, não é possível afirmar que uma seja a causa direta da outra.

Essa análise contribui para uma compreensão mais aprofundada do comportamento dos preços dos combustíveis em relação ao cenário econômico nacional, especialmente no que diz respeito ao impacto sobre o poder de compra da população, onde utilizamos o salário minímo durante o périodo de 2015 a 2025.

## 4. Análise de Distribuições e Visualizações

*Criar gráficos para visualizar o comportamento dos dados (evitar gráfico pizza)*

## 5. Identificação de Problemas nos Dados